# 张量
Tensor


In [57]:
import torch

In [58]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
x.shape

torch.Size([12])

In [60]:
x.numel()

12

In [61]:
X = x.reshape(3, 4)
X = x.reshape(-1, 4)
X = x.reshape(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [62]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [63]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [64]:
# 标准正态分布随机
torch.randn(3,4)

tensor([[-1.9795,  0.3588,  0.8942,  0.5673],
        [-0.4045,  0.5882,  0.2854,  0.1538],
        [ 0.4624,  0.8745,  0.0123,  0.7216]])

In [65]:
x = torch.tensor([1,2,4,6])
y = torch.tensor([2,2,2,2])
x + y

tensor([3, 4, 6, 8])

In [66]:
# 连接
X = torch.tensor([
    [0,0],
    [0,0]
])
Y = torch.tensor([
    [1,1],
    [1,1]
])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[0, 0],
         [0, 0],
         [1, 1],
         [1, 1]]),
 tensor([[0, 0, 1, 1],
         [0, 0, 1, 1]]))

In [67]:
# 广播
X = torch.tensor([
    [0],
    [1],
    [2]
])
Y = torch.tensor([
    [0,1,2]
])
X+Y

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

## 自动微分

In [68]:
x = torch.arange(4.0)
x.requires_grad_(True)
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [69]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [70]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad.zero_()

y = x.sum()
y.backward()
y, x, x.grad

(tensor(6., grad_fn=<SumBackward0>),
 tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([1., 1., 1., 1.]))