In [10]:
import torch

In [11]:
splats = torch.tensor([[10, 10, 10], [20, 20, 20]])
splats

tensor([[10, 10, 10],
        [20, 20, 20]])

In [12]:
splats[[0, 1], [0, 1]]

tensor([10, 20])

In [13]:
dx, dy = torch.meshgrid(torch.arange(4), torch.arange(5), indexing="xy")
dx, dy

(tensor([[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]),
 tensor([[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]]))

In [14]:
coords = torch.stack([dy, dx], dim=2).reshape(-1, 2)
coords

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3]])

In [15]:
splats[:, None, :].shape, coords[None, :, :].shape
torch.cat(
    [
        splats[:, None, :].expand(splats.size(0), coords.size(0), splats.size(1)),
        coords[None, :, :].expand(splats.size(0), coords.size(0), coords.size(1)),
    ],
    dim=-1,
)

tensor([[[10, 10, 10,  0,  0],
         [10, 10, 10,  0,  1],
         [10, 10, 10,  0,  2],
         [10, 10, 10,  0,  3],
         [10, 10, 10,  1,  0],
         [10, 10, 10,  1,  1],
         [10, 10, 10,  1,  2],
         [10, 10, 10,  1,  3],
         [10, 10, 10,  2,  0],
         [10, 10, 10,  2,  1],
         [10, 10, 10,  2,  2],
         [10, 10, 10,  2,  3],
         [10, 10, 10,  3,  0],
         [10, 10, 10,  3,  1],
         [10, 10, 10,  3,  2],
         [10, 10, 10,  3,  3],
         [10, 10, 10,  4,  0],
         [10, 10, 10,  4,  1],
         [10, 10, 10,  4,  2],
         [10, 10, 10,  4,  3]],

        [[20, 20, 20,  0,  0],
         [20, 20, 20,  0,  1],
         [20, 20, 20,  0,  2],
         [20, 20, 20,  0,  3],
         [20, 20, 20,  1,  0],
         [20, 20, 20,  1,  1],
         [20, 20, 20,  1,  2],
         [20, 20, 20,  1,  3],
         [20, 20, 20,  2,  0],
         [20, 20, 20,  2,  1],
         [20, 20, 20,  2,  2],
         [20, 20, 20,  2,  3],
      

In [16]:
features = torch.randn(6, 3)
print("features: \n", features)
group_id = torch.tensor([0, 1, 0, 2, 1, 2])
print("group_id: \n", group_id)

out = torch.zeros(3, 3)
print("out: \n", out)

out.scatter_add_(dim=0, index=group_id[:, None].expand_as(features), src=features)
print("index: \n", group_id[:, None].expand_as(features))

print(out)

features: 
 tensor([[ 0.2784,  0.7148,  0.2272],
        [-0.1504,  0.6964,  0.0074],
        [ 1.3830, -1.1399, -0.0652],
        [-1.0584, -0.1360, -0.6180],
        [-0.6049, -1.2036, -0.9467],
        [ 0.2313, -0.0935, -0.5100]])
group_id: 
 tensor([0, 1, 0, 2, 1, 2])
out: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
index: 
 tensor([[0, 0, 0],
        [1, 1, 1],
        [0, 0, 0],
        [2, 2, 2],
        [1, 1, 1],
        [2, 2, 2]])
tensor([[ 1.6614, -0.4251,  0.1621],
        [-0.7552, -0.5072, -0.9393],
        [-0.8271, -0.2296, -1.1280]])


In [ ]:
coords = torch.tensor([[0, 0], [0, 0], [0, 2]])

values = torch.tensor([[1, 2, 3, 4], [2, 3, 4, 5], [6, 7, 8, 9]])

results = torch.tensor([[1, 2, 3, 4], [3, 5, 7, 9], [6, 7, 8, 9]])

In [17]:
0.2784 + 0.7148 + 0.2272

1.2204